build site:
  image: node:10.12
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist



unit test:
  image: node:10.12
  stage: test
  script:
    - npm install --progress=false
    - npm run test:unit
